name: Go Tests

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [ master ]
    types: [ closed ]

jobs:
  test:
    if: github.event_name != 'pull_request' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 6

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Download dependencies
        run: |
          go mod download

      - name: Run tests
        env:
          DB_CONNECTION_STRING: host=127.0.0.1 user=postgres password=postgres dbname=test port=5432 sslmode=disable TimeZone=UTC
        run: |
          go test ./... -v -coverprofile=coverage.out -covermode=atomic

      - name: Coverage summary
        run: |
          go tool cover -func=coverage.out

      - name: Coverage summary (job summary)
        run: |
          echo '### Coverage' >> $GITHUB_STEP_SUMMARY
          go tool cover -func=coverage.out >> $GITHUB_STEP_SUMMARY

      - name: Coverage HTML report
        run: |
          go tool cover -html=coverage.out -o coverage.html

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            coverage.out
            coverage.html


